---
- hosts: k8s_server
  tasks:
    - name: Test ping
      ping:
    - name: Get ip
      command:
        cmd: ip a
        warn: yes
- hosts: k8s_server
  tasks:
    - name: ensure epel-release latest
      yum: name=epel-release state=latest
    - name: ensure nginx is at the latest version
      yum: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
- hosts: all
  tasks:
    - name: Test ping
      ping:
    - name: Get ip
      command:
        cmd: ip a
        warn: yes
